### ISSUE TITLE
SPL: STM32F401XE.ld: No such file or directory

### ISSUE THREAD

**Issue by ivankravets** [platformio/platform-ststm32#111]
Moved from https://github.com/platformio/platformio-vscode-ide/issues/110

/cc @TheZio69

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platform-ststm32/commit/307dc4e86b29a44930157737e19a8e141105c142

**Comment by Christoph69** [comment]
still having this problem. i updated to the newest version. 
`/Users/christoph/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/bin/ld: cannot open linker script file targets/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F401RE/device/TOOLCHAIN_GCC_ARM/STM32F401XE.ld: No such fileor directory`
