### ISSUE TITLE
Can't (Maple) DFU upload to STM32F103 anymore

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platform-ststm32#855]
Commit https://github.com/platformio/platform-ststm32/commit/4b5ff01c8f91f1a2fd441c593aedfb81aa465f0f removed the usage of the `tool-stm32duino` package in favor of the `tool-stm32flash` package, but the builder script is still expecting the `maple_upload` command to exist.

https://github.com/platformio/platform-ststm32/blob/c8a228c871f5144d63dd78e61bcf548438cbce57/builder/main.py#L238-L248

So, when having a configuration like
```ini
[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = dfu
```

This results in just 
```
> pio run -t upload
Processing bluepill_f103c8 (platform: ststm32; board: bluepill_f103c8; framework: arduino)
...
Looking for upload port...
Auto-detected: /dev/ttyACM0
Uploading .pio/build/bluepill_f103c8/firmware.bin
sh: line 1: maple_upload: command not found
*** [upload] Error 127
```

Judging from https://sourceforge.net/p/stm32flash/code/ci/master/tree/protocol.txt, the stm32flash tool does not support DFU uploads like that at all.

So either we need to bring back `maple_upload` (and that horrible Java thing and batch script logic) or we need to do it with pure dfutil somehow.

**Comment by valeros** [comment]
Thanks @maxgerhardt for pointing it out, should be fixed in the dev branch.

**Comment by FELG14** [comment]
This problem continues to occur. I already tried it with the new commit and it is still the same. Please check it.

**Comment by FELG14** [comment]
```
C:\Users\Usuario\.platformio\penv\Scripts\pio.exe run -t upload -e bluepill_f103c8
[0m[0mProcessing bluepill_f103c8 (platform: https://github.com/platformio/platform-ststm32.git; board: bluepill_f103c8; framework
: arduino)
---------------------------------------------------------------------------------------------------------------------------

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/bluepill_f103c8.html
PLATFORM: ST STM32 (19.2.0+sha.0459d32) > BluePill F103C8
HARDWARE: STM32F103C8T6 72MHz, 20KB RAM, 64KB Flash
DEBUG: Current (stlink) External (blackmagic, cmsis-dap, jlink, stlink)
PACKAGES:
 - framework-arduinoststm32 @ 4.21001.250617 (2.10.1)
 - framework-cmsis @ 2.50900.0 (5.9.0)
 - tool-dfuutil @ 1.11.0
 - tool-dfuutil-arduino @ 1.11.0
 - tool-openocd @ 3.1200.0 (12.0)
 - tool-stm32duino @ 1.0.2
 - tool-stm32flash @ 0.7.0
 - toolchain-gccarmnoneeabi @ 1.120301.0 (12.3.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 14 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Compiling .pio\build\bluepill_f103c8\FrameworkArduinoVariant\PeripheralPins.c.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduinoVariant\PeripheralPins_MALYANM200_F103CB.c.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduinoVariant\generic_clock.c.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduinoVariant\startup_M200_f103xb.S.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduinoVariant\variant_AFROFLIGHT_F103CB.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduinoVariant\variant_MALYANM200_F103CB.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduinoVariant\variant_MAPLEMINI_F103CB.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduinoVariant\variant_PILL_F103Cx.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduinoVariant\variant_generic.cpp.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_adc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_adc_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_can.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_ccb.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_cec.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_comp.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_comp_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_cordic.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_cortex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_crc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_crc_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_cryp.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_cryp_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_dac.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_dac_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_dcache.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_dcmi.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_dcmi_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_dfsdm.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_dfsdm_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_dma.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_dma2d.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_dma_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_dsi.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_dts.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_eth.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_eth_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_exti.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_fdcan.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_firewall.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_flash.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_flash_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_flash_ramfunc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_fmac.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_fmpi2c.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_fmpi2c_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_fmpsmbus.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_fmpsmbus_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_gfxmmu.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_gfxtim.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_gpio.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_gpio_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_gpu2d.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_gtzc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_hash.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_hash_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_hcd.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_hrtim.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_hsem.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_i2c.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_i2c_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_i2s.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_i2s_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_i3c.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_icache.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_ipcc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_irda.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_iwdg.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_jpeg.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_lcd.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_lptim.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_ltdc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_ltdc_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_mdf.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_mdios.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_mdma.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_mmc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_mmc_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_nand.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_nor.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_opamp.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_opamp_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_ospi.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_otfdec.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_pccard.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_pcd.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_pcd_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_pka.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_pssi.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_pwr.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_pwr_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_qspi.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_ramcfg.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_ramecc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_rcc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_rcc_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_rng.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_rng_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_rtc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_rtc_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_sai.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_sai_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_sd.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_sd_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_sdadc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_sdio.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_sdram.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_smartcard.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_smartcard_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_smbus.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_smbus_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_spdifrx.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_spi.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_spi_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_sram.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_subghz.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_swpmi.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_tim.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_tim_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_tsc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_uart.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_uart_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_usart.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_usart_ex.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_wwdg.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HAL\stm32yyxx_hal_xspi.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\HardwareTimer.cpp.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_adc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_bdma.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_comp.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_cordic.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_crc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_crs.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_dac.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_delayblock.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_dlyb.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_dma.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_dma2d.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_exti.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_fmac.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_fmc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_fmpi2c.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_fsmc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_gpio.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_hrtim.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_i2c.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_i3c.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_icache.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_lpgpio.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_lptim.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_lpuart.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_mdma.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_opamp.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_pka.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_pwr.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_rcc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_rng.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_rtc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_sdmmc.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_spi.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_swpmi.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_tim.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_ucpd.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_usart.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_usb.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\LL\stm32yyxx_ll_utils.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\new.cpp.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\stm32\PortNames.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\stm32\analog.cpp.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\stm32\bootloader.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\stm32\clock.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\stm32\core_callback.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\stm32\dwt.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\stm32\hw_config.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\stm32\interrupt.cpp.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\stm32\otp.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\stm32\pinmap.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\stm32\stm32_def.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\stm32\system_stm32yyxx.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\stm32\timer.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\stm32\uart.c.o
Compiling .pio\build\bluepill_f103c8\SrcWrapper\src\syscalls.c.o
Compiling .pio\build\bluepill_f103c8\src\main.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\HardwareSerial.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\IPAddress.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\Print.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\RingBuffer.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\Stream.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\Tone.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\WInterrupts.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\WMath.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\WSerial.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\WString.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\abi.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\avr\dtostrf.c.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\board.c.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\core_debug.c.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\hooks.c.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\itoa.c.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\main.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\pins_arduino.c.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\stm32\startup_stm32yyxx.S.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\wiring_analog.c.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\wiring_digital.c.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\wiring_pulse.cpp.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\wiring_shift.c.o
Compiling .pio\build\bluepill_f103c8\FrameworkArduino\wiring_time.c.o
Archiving .pio\build\bluepill_f103c8\libFrameworkArduino.a
Linking .pio\build\bluepill_f103c8\firmware.elf
Checking size .pio\build\bluepill_f103c8\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]   5.3% (used 1076 bytes from 20480 bytes)
Flash: [=         ]  10.8% (used 7088 bytes from 65536 bytes)
Building .pio\build\bluepill_f103c8\firmware.bin
Configuring upload protocol...
AVAILABLE: blackmagic, cmsis-dap, dfu, jlink, mbed, stlink
CURRENT: upload_protocol = dfu
Looking for upload port...
Auto-detected: COM1
Uploading .pio\build\bluepill_f103c8\firmware.bin
"maple_upload" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
*** [upload] Error 1
=============================================== [FAILED] Took 15.08 seconds ===============================================



``
```

**Comment by valeros** [comment]
@FELG14 Thanks for reporting, please retest with the latest version from this repo.

**Comment by FELG14** [comment]
> [@FELG14](https://github.com/FELG14) Thanks for reporting, please retest with the latest version from this repo.

Thank you very much, it works now without any problems.
